#!/bin/bash

DB_FOLDER="/home/yaron/projects/shoam/db"
CACHE_FILE=$DB_FOLDER/courses_cache

fast_access () {
    touch tmp 

    for f in $DB_FOLDER/* 
    do
        code=${f#*/db/}
        code=${code%%-*}
        name=$(cat $f | sed -n '/Name/{n;p;q;}')
        echo $code, $name >> tmp 
    done

    cat tmp | sort | uniq > $CACHE_FILE 
    rm tmp
}

if [ ! -e $CACHE_FILE ]; then
    fast_access
fi
